spring.application.name=api-service

# URL de la base de données (remplacez 'ma_base' par le nom de votre DB)
spring.datasource.url=jdbc:postgresql://localhost:5433/education

# Vos identifiants PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=mon_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# On désactive la création automatique de Spring...
spring.jpa.hibernate.ddl-auto=update

# ...pour dire à Spring de lancer toujours notre fichier schema.sql
spring.sql.init.mode=always

# Pour voir les requêtes SQL dans la console (très pratique pour débugger)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
