CREATE TABLE IF NOT EXISTS ETUDIANT (
    id VARCHAR(10) PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENSEIGNANT (
    id VARCHAR(10) PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS COURS (
    id VARCHAR(16) PRIMARY KEY,
    titre VARCHAR(64) NOT NULL,
    departement VARCHAR(128) NOT NULL,
    credit INT NOT NULL,
    descript TEXT NOT NULL,
    horaire DATE NOT NULL,
    salle VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS ETUDIANTCOURS (
    id VARCHAR(10) PRIMARY KEY,
    etudiant_id VARCHAR(10) NOT NULL,
    cours_id VARCHAR(10) NOT NULL,
    FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    FOREIGN KEY (cours_id) REFERENCES cours(id)
);

CREATE TABLE IF NOT EXISTS ENSEIGNANTCOURS (
    id VARCHAR(10) PRIMARY KEY,
    enseignant_id VARCHAR(10) NOT NULL,
    cours_id VARCHAR(10) NOT NULL,
    FOREIGN KEY (enseignant_id) REFERENCES enseignant(id),
    FOREIGN KEY (cours_id) REFERENCES cours(id)
);
